# URL de producción en GitHub Pages
baseURL = "https://danielrn13.github.io/"
languageCode = "es-mx"
title = "Monalisa Crepes & Burgers"
theme = "ananke"

[params]
  author = "Mona"
  description = "Las mejores crepas y hamburguesas artesanales."
  featured_image = "/images/banner-principal.jpg"
  custom_css = ["css/custom.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "Inicio"
  url = "/"
  weight = 10